### ISSUE TITLE
Provide specific value for invalid value for PathPropertiesConstraint

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-openapitools#24]
Hello,

It would be interesting to be able to have an `invalid_value` parameter like for the `PropertyValueConstraint`, but with the `PathPropertiesConstraint`

Maybe it would even be more interesting to have a method similar to `get_relations` and `get_parameter_relations` but for the url parameters `get_url_relations`, that way we could fine tune each parameter of the url individually.

I also noticed that the `PathPropertiesConstraint` contains `propertyName` and `error_code` attributes that does not seem to be used at all

Thanks

**Comment by robinmackaij** [comment]
What would the use case be for this? I added `PathPropertiesConstraint` for cases where a path needs to include a reference to an id / uuid of a resource that cannot be retrieved within the scope of that API / OAS (e.g. a `TenantId` in a path). Since we're doing http, any url that gets constructed based on the path information that does not exist, should result in a 404.

When there is a PathPropertiesConstraint, the value it returns is used as-is. Within the Dto, you can put whatever logic you need to construct that value.

The mentioned attributes are indeed there and unused. This is due to the inheritance structure for Dtos.

**Comment by Leemur89** [comment]
In some cases a resource can exist but the system wants to hide it because the user requesting the access has not sufficient permission (a 403 response would disclose to the user that the resource well exist, whereas in this case we do not want to disclose that the resource exist)
cf https://httpwg.org/specs/rfc7231.html#status.403

As it is a specific case of 403, an alternative would be to have the expected status in the `Test Forbidden` parameter, with a default value of 403, but for which we could change to 404

**Comment by Leemur89** [comment]
Actually the `Test Forbidden` will not work in my case because the body validation happens before the data lookup/access verification and as currently the `Test Forbidden` does not send a body I'm getting 400

**Comment by robinmackaij** [comment]
I'm inclined to say that for specific authorization checks like these, using OpenApiLibCore to create specific test cases for the specific endpoints is the way to go. The keywords `Get Valid Url` and `Get Request Data`  can be used to get the data needed to pass to `Authorized Request` for a 200, but you can pass other headers than generated by `Get Request Data` to `Authorized Request` to validate the responses for different authorization levels. `Get Request Data` return the Python `requests` `Response` object, where you can check the status code, response body, etc.

OpenApiDriver was never meant to cover authorization scenarios, also due to the fact that the OAS holds no information about access levels on an endpoint basis (and from a security point of view, it'd often be obfuscated / left out on purpose).

**Comment by Leemur89** [comment]
Indeed using OpenApiLibCore is far more effective in my case and provide more flexibility
thanks
